export {
  ACTIVE_STATUSES,
  FLEET_COVERAGE,
  FLEET_DRIVER,
  FLEET_VEHICLE,
  activeTrip,
  availableTrips,
  demoNotifications,
  demoTrips,
  earningsChartData,
  isActiveStatus,
  logisticsEarningsSummary,
  logisticsNotifications,
  logisticsRecentPayments,
  logisticsTripHistory,
  logisticsVehicles,
  myTrips,
  recentPayments,
  tripHistory,
  vehicles,
} from "@/mock-data/adapters/logistics";
